# Generated by Django 3.1 on 2020-08-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=16)),
                ('desc', models.CharField(max_length=600)),
                ('pub_date', models.DateField()),
                ('Image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
